apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {  # 모든 도메인 요청(:53 포트)을 처리함 (기본 DNS 포트)
        errors  # DNS 오류를 로깅함

        health {
           lameduck 5s  # 종료 직전 5초 동안 트래픽 받지 않음 (graceful shutdown용)
        }

        ready  # CoreDNS가 준비되었는지 헬스체크하는 엔드포인트 지원

        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure  # Pod 이름 기반 DNS 허용 (보안 인증 없이)
           fallthrough in-addr.arpa ip6.arpa  # 요청이 여기서 실패하면 다음 플러그인으로 넘김
           ttl 30  # 캐시 TTL을 30초로 설정
        }

        prometheus :9153  # Prometheus 메트릭을 9153 포트로 노출

        forward . 8.8.8.8 1.1.1.1 {
           max_concurrent 1000  # 외부 DNS로의 동시 요청 수 제한 (최대 1000개)
        }

        cache 30 {
           disable success cluster.local  # cluster.local 도메인 요청은 성공 캐시 안 함
           disable denial cluster.local  # cluster.local 도메인 요청 실패도 캐시 안 함
        }

        loop  # 무한 재귀 요청 감지 방지 (자기 자신으로의 DNS 루프)
        reload  # ConfigMap 변경 시 자동으로 설정 재로드
        loadbalance  # 여러 upstream DNS 서버에 대해 로드밸런싱 수행
    }
